feat: add codefreeze action
stampedeapp/actions pull request #14
Opened 2022-10-19 11:32 UTC by csaunders-ldt

draft pr

2022-10-19 12:53 UTC, LukeSheard requested changes
I would write this using JS as I'm pretty sure it will be cleaner than `eval` yaml code into another action.

2022-10-19 13:20 UTC, csaunders-ldt commented
> I would write this using JS as I'm pretty sure it will be cleaner than `eval` yaml code into another action.

I've modified the code to use GHA syntax for errors - slightly less clean as it shows 2 exit codes, but saves using an action.

As we had discussed in PM prior to this comment, I really want to avoid javascript actions where possible - GHA clones the entire repository every time, so any javascript actions slow down all action runs across the board, and startup time is 1-2 seconds higher anyway (plus it adds an extra layer of obfuscation). Definitely not worth it in this case.

2022-10-19 13:59 UTC, LukeSheard commented on check-code-freeze/action.yml
> +name: Run Cypress
name

2022-10-19 13:59 UTC, LukeSheard commented on check-code-freeze/action.yml
> +  github-token:
I'm assuming this is just `secrets.GITHUB_TOKEN` ?

2022-10-19 16:36 UTC, csaunders-ldt commented on check-code-freeze/action.yml
> +  github-token:
Annoyingly, it can't be `secrets.GITHUB_TOKEN`, it's the only token they don't allow. Otherwise it can be any valid Github Token - I've added a global PAT token for this action.

2022-10-19 16:37 UTC, csaunders-ldt commented on check-code-freeze/action.yml
> +name: Run Cypress
lol. fixed.

2022-10-21 10:29 UTC, leaky commented on check-code-freeze/action.yml
> +          echo "::error::Workflow failed due to code freeze in effect (${{ steps.check-file.outputs.reason }})"
Being pedantic but can we change the wording to say the workflow hasn't run/is paused instead? It hasn't failed.

2022-10-21 10:50 UTC, trevorah approved these changes
I'm happy with bash for simple things, but from experience with pipeline actions that could be written in bash or js, I think the tipping point is when you want to write tests for your script. You can write tests for bash, but people will throw things at you.

I would say that you are 1 `if` statement away from writing this in js.

2022-10-21 10:50 UTC, trevorah commented on check-code-freeze/action.yml
> +description: Clones the repository, installs dependencies, and runs Cypress.
```suggestion
description: Fails the build if a code freeze is currently active.
```

2022-10-21 12:08 UTC, merged